add_tracking:
  fields:
    tracking_id:
      required: true
      example: "370000000000123456"
      selector:
        text:
    carrier:
      required: false
      selector:
        select:
          options:
            - label: "Bring (Posten Norge)"
              value: "bring"
            - label: "Postnord"
              value: "postnord"
            - label: "Helthjem"
              value: "helthjem"

remove_tracking:
  fields:
    tracking_id:
      required: true
      example: "370000000000123456"
      selector:
        text:
